config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :campings do  
      get :home, on: :collection 
      get :search, on: :collection
      get :my_campings, on: :collection
      get :admin_camp, on: :member
      get :find_address, on: :collection
      resources :campsites
      resources :campservices
      resources :plans
      resources :bookings do
        get :prepayment, on: :member
        resources :reviews
      end
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  resources :users, only: [] do 
    get 'user_bookings', to: 'bookings#user_bookings'
    get :find_address, on: :collection
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
      
  get 'regions', to: 'regions#new'
  get 'cities', to: 'cities#new'
  get 'communes', to: 'communes#new'

  root 'campings#home'

  get  '*path' => redirect('campings/home')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/camping.rb
class Camping < ApplicationRecord
  belongs_to :user
  belongs_to :commune
  belongs_to :country, optional: true
  enum camping_type: [:camping, :patio]
  mount_uploaders :images, ImageUploader
  has_many :campsites
  has_and_belongs_to_many :services
  has_many :plans
  has_many :bookings, through: :campsites
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  validates :name, :user_id, :camping_type, :commune_id, presence: true

  def prom(id) 
    reviews = Review.where(booking_id: Booking.where(campsite_id: Campsite.where(camping_id: id)))
    
    if reviews.count > 0
      suma = 0
      reviews.each do |review|
        suma += review.ranking
      end

      @prom = suma / reviews.count
    else 
      @prom = 'No hay evaluaciones aun.'
    end

  end

end

app/controllers/campings_controller.rb
class CampingsController < ApplicationController
  before_action :set_camping, only: [:show, :edit, :update, :destroy,:admin_camp]

  def index
    if params[:desitino] != ""
      @campings = Camping.where(commune_id: Commune.where("name LIKE ?", "%#{params[:destino]}%").select(:id)).page(params[:page]).per(9)
      @camps = Camping.where(commune_id: Commune.where("name LIKE ?", "%#{params[:destino]}%").select(:id)).count
    elsif params[:check_in] != "" and params[:check_out] != ""
      @campings = Camping.select(:id,:name,:commune_id).distinct.joins(:campsites).where.not(campsites: {id: Booking.where("(check_in <= ? and check_out >= ?) or (check_in < ? and check_out >= ?) or (? <= check_in and ? >= check_in)", params[:check_in],params[:check_out], params[:check_in], params[:check_in],params[:check_out],params[:check_in]).select(:campsite_id)}).where(commune_id: Commune.where("name LIKE ?", "%#{params[:destino]}%").select(:id)).page(params[:page]).per(9)
      @camps = Camping.select(:id).distinct.joins(:campsites).where.not(campsites: {id: Booking.where("(check_in <= ? and check_out >= ?) or (check_in < ? and check_out >= ?) or (? <= check_in and ? >= check_in)", params[:check_in],params[:check_out], params[:check_in], params[:check_in],params[:check_out],params[:check_in]).select(:campsite_id)}).where(commune_id: Commune.where("name LIKE ?", "%#{params[:destino]}%").select(:id)).count
    else
      @campings = Camping.order(:name).page(params[:page]).per(9)
      @camps = Camping.all.count
    end  
    
    if user_signed_in?
  		campings_map = Camping.near(current_user.address, 200, units: :km)
  	else
  		campings_map = Camping.all
  	end

	  @hash = Gmaps4rails.build_markers(campings_map) do |camping, marker|
		  marker.lat camping.latitude
		  marker.lng camping.longitude
    end

  end

  def my_campings
    @campings = Camping.where(user_id: current_user)
  end

  def home

  end

  def new
    authorize! :new, Camping
    @country = Country.all
    @camping = Camping.new
  end

  def create
    authorize! :create, Camping
  	camping = Camping.new(camping_params)
    camping.user = current_user
    if camping.save
      redirect_to camping_path(camping), notice: 'Se creo camping con exito'
    else
      redirect_to new_camping_path, notice: 'No se pudo crear camping :('
    end
  end

  def show
    @plans_high = @camping.plans.where(season_id: 1).pluck(:person_type,:price)
    @plans_low = @camping.plans.where(season_id: 2).pluck(:person_type,:price)
    @services = @camping.services
    @reviews = Review.where(booking_id: Booking.where(campsite_id: Campsite.where(camping_id: @camping)))
  end

  def edit
    authorize! :edit, Camping
    @country = Country.all
  end

  def update
    authorize! :update, Camping
    if @camping.update(camping_params)
      redirect_to camping_path(@camping), notice: 'El Camping se ha actualizado con exito'
    else
      redirect_to edit_camping_path(@camping.id), notice: 'No se ha podido actualizar el registro'
    end
  end

  def destroy
    authorize! :destroy, Camping
    @camping.destroy
    redirect_to campings_path, notice: 'El registro se ha eliminado con exito'
  end

  def admin_camp
    
  end

  def find_address
    response = { address: Geocoder.address([params[:latitude], params[:longitude]]) }
    render json: response.to_json
  end
  
  def return_cities
    @cities = City.where(region_id: params[:region_id])
  end

  def return_communes
    @communes = Commune.where(city_id: params[:city_id])
  end

  private

  def set_camping
    @camping = Camping.find(params[:id])
  end
  
  def camping_params
    params.require(:camping).permit(:name,:description,:user_id, :phone, :email,:web,:facebook, :tourism,:camping_type,:commune_id,:address,:latitude,:longitude,:info, {images: []}, service_ids:[])
  end
  
end

app/helpers/campings_helper.rb
module CampingsHelper
end

app/views/campings/_form.html.erb
<div class="gtco-section border-bottom">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-6 animate-box">
					<h3>Completa los siguientes datos:</h3>
					<%= form_with(model: @camping, local: true) do |f| %>
						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :name, 'Nombre:' %>
								<%= f.text_field :name, autofocus: true, class: "form-control" %>
							</div>
							
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :description, 'Descripcion:' %>
                                <%= f.text_area :description, class: "form-control", cols: "30", rows: "5" %>
                            </div>
						</div>

                        <div class="row form-group">
							<div class="col-md-12">
								<%= f.label :phone,'Teléfono:' %>
                                <%= f.text_field :phone, class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :email,'Email:' %>
                                <%= f.text_field :email, class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :web,'Web:' %>
                                <%= f.text_field :web, class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :facebook,'Facebook:' %>
                                <%= f.text_field :facebook, class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :camping_type, 'Tipo de Camping:' %><br>
								<p>*Recuerda que puedes rentar tu patio o tu propio Camping</p>
	    						<%= f.select :camping_type, Camping.camping_types.keys, prompt: 'Seleccione Tipo Camping',class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :address,'Dirección:' %>
                                <%= f.text_field :address, class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :country,'País:' %><br>
                                <%= f.select :country, @country.pluck(:name, :id), prompt: 'Seleccione Pais', class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :region,'Región:' %>
                                <select id="regions" class="form-control"></select>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :city,'Ciudad:' %>
                                <select id="cities" class="form-control"></select>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :commune,'Comuna:' %>
                                <select id="commune_id" name="camping[commune_id]"></select>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :info, 'Información adicional:' %>
                                <%= f.text_area :info, class: "form-control", cols: "30", rows: "10", placeholder: "Indicanos más información que consideres importante, por ejemplo reglas de lugar, disponibilidad horaria de las duchas, etc" %>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :tourism, 'Turismo en la Zona:' %>
                                <%= f.text_area :tourism, class: "form-control", cols: "30", rows: "10", placeholder: "Cuentanos las atracciones turisticas cercanas a tu Camping" %>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :images, 'Imagenes de tu Camping:' %>
								<p>Puedes subir más de una imagen!</p>
                                <%= f.file_field :images, id: :image_image, multiple: true, class: "form-control" %>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :services, 'Servicios que Ofreces:' %>
								<%= f.collection_check_boxes :service_ids, Service.all, :id, :name do |b| %>
									<div class="collection-check-box">
										<%= b.check_box %>
										<%= b.label %>
									</div>
								<% end %>
                            </div>
						</div>

						<div class="form-group">
                            <%= f.submit 'Guardar', class: "btn btn-primary"  %>
						</div>

					</form>	
                    <% end %>	
				</div>
				
				</div>
			</div>
		</div>
	</div>

<script>

	$('select[name="camping[country]"]').on('change', function(event){
		$.ajax({
			url: '<%= regions_path %>',
			type: 'get',
			dataType: 'script',
			data: {country_id: $(this).val()}
		})
	})

	$('#regions').on('change', function(event){
		$.ajax({
			url: '<%= cities_path %>',
			type: 'get',
			dataType: 'script',
			data: {region_id: $(this).val()}
		})
	})

	$('#cities').on('change', function(event){
		$.ajax({
			url: '<%= communes_path %>',
			type: 'get',
			dataType: 'script',
			data: {city_id: $(this).val()}
		})
	});
</script>

app/views/campings/admin_camp.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-center">
					<div class="row row-mt-15em">

						<div class="col-md-12 mt-text animate-box" data-animate-effect="fadeInUp">
							<h1></h1>	
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	<p><%= notice %></p>
    <p><%= alert %></p>

	<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Administrar Camping</h2>
						<ul class="pricing-info">
                            <%= link_to 'Mis Sitios', camping_campsites_path(@camping), class: "btn btn-dark"%>
                            <%= link_to 'Mis Planes', camping_plans_path(@camping), class: "btn btn-dark"%>
                            <%= link_to 'Mis Reservas', camping_bookings_path(@camping), class: "btn btn-dark"%>
							<%= link_to 'Editar Camping', edit_camping_path(@camping), class: "btn btn-dark"%>
                        </ul>
				</div>
			</div>

			<div class="row">
				
			</div>
		</div>
	</div>
    

app/views/campings/edit.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
				
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>
	
	<%= render 'form'%>

<script>
	if (navigator.geolocation) {
 		navigator.geolocation.getCurrentPosition(getAddress);
	} else {
 		x.innerHTML = "Geolocation is not supported by this browser.";
 	}
 	function getAddress(position) {
 		var latitude = position.coords.latitude;
 		var longitude = position.coords.longitude;
 		$.ajax({
 		url: '<%= find_address_campings_path %>',
 		type: 'GET',
 		dataType: 'json',
 		data: {latitude: latitude, longitude: longitude}
 		});
 	};
</script>

app/views/campings/home.html.erb
<div class="gtco-loader"></div>
	
<div id="page">
	
	<header id="gtco-header" class="gtco-cover gtco-cover-md cover" role="banner" style="">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					

					<div class="row row-mt-15em">
						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<h1>Reencuentrate con la Naturaleza...</h1>	
						</div>
						<div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
							<div class="form-wrap">
								<div class="tab">
									
									<div class="tab-content">
										<div class="tab-content-inner active" data-content="signup">
											<h3>Encuentra tu Camping</h3>
											<%= form_with(url: campings_path, local: true, method: :get) do |f| %>
												<div class="row form-group">
													<div class="col-md-12">
														<%= f.label :destino, 'Destino:' %>
														<%= f.text_field :destino, autofocus: true, class: "form-control", required: true %>
													</div>
												</div>
												
												<div class="row form-group">
													<div class="col-md-12">
														<%= f.label :check_in, 'Desde:' %>
														<%= f.date_field :check_in, class: "form-control"%>
													</div>
												</div>

												<div class="row form-group">
													<div class="col-md-12">
														<%= f.label :check_out, 'Hasta:' %>
														<%= f.date_field :check_out, class: "form-control"%>
													</div>
												</div>

												<div class="row form-group">
													<div class="col-md-12">
														<input type="submit" class="btn btn-primary btn-block" value="Buscar">
													</div>
												</div>
											<%end%>	
										</div>

										
									</div>
								</div>
							</div>
						</div>
					</div>
							
					
				</div>
			</div>
		</div>
	</header>
	
	<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Destinos Populares</h2>
					<p>Conoce las regiones más visitadas de Chile por nuestros Usuarios.</p>
				</div>
			</div>
			<div class="row">

				<div class="col-lg-4 col-md-4 col-sm-6">
				   <a href="<%= campings_path %>" class="fh5co-card-item">		
						<figure>
							<div class="overlay"></div>
							<%= image_tag 'atacama.jpg', class: "img-responsive" %>
						</figure>
						<div class="fh5co-text">
							<h2>Región de Atacama</h2>
							<p>Famosa por su hermosa ciudad de San Pedro y el Desierto florido.</p>
						</div>
					</a>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-6">
					<a href="<%= campings_path %>" class="fh5co-card-item">
						<figure>
							<div class="overlay"></div>
							<%= image_tag 'magallanes.jpg', class: "img-responsive" %>
						</figure>
						<div class="fh5co-text">
							<h2>Región de Magallanes</h2>
							<p>Famosa por las hermosas Torres del Paine y sus Lagos.</p>
						</div>
					</a>
				</div>
				<div class="col-lg-4 col-md-4 col-sm-6">
					<a href="<%= campings_path %>" class="fh5co-card-item">
						<figure>
							<div class="overlay"></div>
							<%= image_tag 'loslagos.jpg', class: "img-responsive" %>
						</figure>
						<div class="fh5co-text">
							<h2>Región de Los Lagos</h2>
							<p>Famosa por sus bosques, hermosos lagos y montañas.</p>
						</div>
					</a>
				</div>


				<div class="col-lg-4 col-md-4 col-sm-6">
					<a href="<%= campings_path %>" class="fh5co-card-item">
						<figure>
							<div class="overlay"></div>
							<%= image_tag 'coquimbo.jpg', class: "img-responsive" %>
						</figure>
						<div class="fh5co-text">
							<h2>Región de Coquimbo</h2>
							<p>Famosa por el Valle del Elqui, su hermoso cielo y su Pisco.</p>
						</div>
					</a>
				</div>

				<div class="col-lg-4 col-md-4 col-sm-6">
					<a href="<%= campings_path %>" class="fh5co-card-item">
						<figure>
							<div class="overlay"></div>
							<%= image_tag 'metropolitana.jpg', class: "img-responsive" %>
						</figure>
						<div class="fh5co-text">
							<h2>Región Metropolitana</h2>
							<p>Famosa por su cercanía a la Cordillera de los Andes.</p>
						</div>
					</a>
				</div>

				<div class="col-lg-4 col-md-4 col-sm-6">
					<a href="<%= campings_path %>" class="fh5co-card-item">
						<figure>
							<div class="overlay"></div>
							<%= image_tag 'maule.jpg', class: "img-responsive" %>
						</figure>
						<div class="fh5co-text">
							<h2>Región del Maule</h2>
							<p>Famosa por el Parque de las Siete Tazas y sus viñas</p>
						</div>
					</a>
				</div>

			</div>
		</div>
	</div>
	
	<div id="gtco-features">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2>Nuestra Meta</h2>
					<p>Fomentar el turismo de Campings dentro de Chile, para que más personas se conecten con nuestra hermosa Naturaleza.</p>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i>1</i>
						</span>
						<h3>Conoce Chile!</h3>
						<p>Planifica tus proximas vacaciones y reserva tu Camping en un click!</p>
					</div>
				</div>
				<div class="col-md-4 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i>2</i>
						</span>
						<h3>Inscribe tu Camping!</h3>
						<p>Eres dueño de un Camping y te gustaría ser parte de nuestro sitio? Estas a un click de hacerlo!</p>
					</div>
				</div>
				<div class="col-md-4 col-sm-6">
					<div class="feature-center animate-box" data-animate-effect="fadeIn">
						<span class="icon">
							<i>3</i>
						</span>
						<h3>Arrienda tu Patio!</h3>
						<p>Tienes un patio enorme y te gustaría rentarlo? Estas en el sitio correcto! </p>
					</div>
				</div>
				

			</div>
		</div>
	</div>

	<div id="gtco-counter" class="gtco-section">
		<div class="gtco-container">

			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2>Seguimos creciendo!</h2>
					<p>Muchos chilenos ya han confiado en nosotros, unete! No esperes más :)</p>
				</div>
			</div>

			<div class="row">
				
				<div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInUp">
					<div class="feature-center">
						<span class="counter js-counter" data-from="0" data-to="196" data-speed="5000" data-refresh-interval="50">1</span>
						<span class="counter-label">Destinos</span>

					</div>
				</div>
				<div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInUp">
					<div class="feature-center">
						<span class="counter js-counter" data-from="0" data-to="230" data-speed="5000" data-refresh-interval="50">1</span>
						<span class="counter-label">Campings</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInUp">
					<div class="feature-center">
						<span class="counter js-counter" data-from="0" data-to="3548" data-speed="5000" data-refresh-interval="50">1</span>
						<span class="counter-label">Viajeros</span>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 animate-box" data-animate-effect="fadeInUp">
					<div class="feature-center">
						<span class="counter js-counter" data-from="0" data-to="3378" data-speed="5000" data-refresh-interval="50">1</span>
						<span class="counter-label">Usuarios Felices :)</span>

					</div>
				</div>
					
			</div>
		</div>
	</div>

	

	<div id="gtco-subscribe">
		<div class="gtco-container">
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Suscribete a nuestro Sitio</h2>
					<p>Conoce el mundo del Camping en Chile</p>
				</div>
			</div>
			<div class="row animate-box">
				<div class="col-md-8 col-md-offset-2">
					<form class="form-inline">
						<div class="col-md-6 col-sm-6">
							<div class="form-group">
								<label for="email" class="sr-only">Email</label>
								<input type="email" class="form-control" id="email" placeholder="ejemplo@ejemplo.cl">
							</div>
						</div>
						<div class="col-md-6 col-sm-6">
							<button type="submit" class="btn btn-default btn-block">Suscribir</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- </div> -->
	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop">**</a>
	</div>
	
	

app/views/campings/my_campings.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-center">
					<div class="row row-mt-15em">

						<div class="col-md-12 mt-text animate-box" data-animate-effect="fadeInUp">
							<h1></h1>	
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	<p><%= notice %></p>
    <p><%= alert %></p>
	<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Mis Campings</h2>
				</div>
			</div>

			<div class="row">
				<% @campings.each do |camping| %>
					<div class="col-lg-4 col-md-4 col-sm-6">
							<figure>
								<div class="overlay"></div>
								<%= image_tag 'magallanes.jpg', class: "img-responsive" %>
							</figure>
							<div class="fh5co-text">
								<h2><%= camping.name %></h2>
								<p><%= camping.description %></p>
								<%= link_to 'Ver Camping', admin_camp_camping_path(camping), class: "btn btn-dark"%>
								<br><br>
							</div>
					</div>
					<% end %>
			</div>
		</div>
	</div>

app/views/campings/show.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-center">
					<div class="row row-mt-15em">

						<div class="col-md-12 mt-text animate-box" data-animate-effect="fadeInUp">
							<h1>Bienvenido a <%= @camping.name %></h1>	
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
	<p><%= notice %></p>
    <p><%= alert %></p>
	
	<div class="gtco-section border-bottom">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<p><%= @camping.description %></p>
				</div>
			</div>
			<div class="row">
			
				<div class="col-md-4">
					
					<div class="price-box popular">
						<h2 class="pricing-plan">Precios</h2>
						<hr>
						<ul class="pricing-info">
							<h4>Temporada Alta: </h4>
							<%if @plans_high == []%>
								<li>No hay precios asociados a temporada alta aun :(</li><br>
							<%else%>
								<li>Adulto: <%= @plans_high[1][1] %></li>
								<li>Niño: <%= @plans_high[0][1] %></li><br>
							<%end%>
							<h4>Temporada Baja: </h4>
							<%if @plans_low == []%>
								<li>No hay precios asociados a temporada baja aun :(</li>
							<%else%>
								<li>Adulto: <%= @plans_low[1][1] %></li>
								<li>Niño: <%= @plans_low[0][1] %></li>
							<%end%>
						</ul>
						<%= link_to 'Reserva Ahora!', new_camping_booking_path(@camping), class: "btn btn-primary btn-sm"%>
					</div>
				</div>
				<div class="col-md-4">
					<div class="price-box popular">
						<h2 class="pricing-plan">Servicios</h2>
						<hr>
						<ul class="pricing-info">
						<%if @services.empty?%>
								<p>No hay descripción de servicios aun.</p>
							<%else%>
								<% @services.each do |servicio| %>
									<li><%= servicio.name %></li>
								<% end %>
							<%end%>
						</ul>
						<%= link_to 'Reserva Ahora!', new_camping_booking_path(@camping), class: "btn btn-primary btn-sm"%>
					</div>
				</div>
				<div class="col-md-4">
					<div class="price-box popular">
						<h2 class="pricing-plan">Turismo:</h2>
						<hr>
						<ul class="pricing-info">
							<%if @camping.tourism.empty?%>
								<p>No hay sugerencias de turismo en la zona aun</p>
							<%else%>
								<li><%= @camping.tourism %></li>
							<%end%>
						</ul>
						<%= link_to 'Reserva Ahora!', new_camping_booking_path(@camping), class: "btn btn-primary btn-sm"%>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2>Información adicional:</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<ul class="fh5co-faq-list">
						<li class="animate-box">
						<%if @camping.info.empty?%>
							<p>No hay información adicional</p>
						<%else%>
							<p><%= @camping.info %></p>
						<%end%>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2>Opiniones Usuarios</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<ul class="price-box popular">
						<%if @reviews.empty?%>
							<p>No hay opiniones asociadas al Camping aun.</p>
						<%else%>
							<% @reviews.each do |review| %>
									<h4>El <%= review.created_at.strftime("%d-%m-%Y") %> <%= review.booking.user.name%> escribió:</h4>
									<p><%= review.comment %></p>
									<p>Evaluación: <%= review.ranking.to_i %></p>
							<% end %>
						<%end%>
					</ul>
				</div>
			</div>
		</div>
	</div>