config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :campings do  
      get :home, on: :collection 
      get :search, on: :collection
      get :my_campings, on: :collection
      get :admin_camp, on: :member
      get :find_address, on: :collection
      resources :campsites
      resources :campservices
      resources :plans
      resources :bookings do
        get :prepayment, on: :member
        resources :reviews
      end
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  resources :users, only: [] do 
    get 'user_bookings', to: 'bookings#user_bookings'
    get :find_address, on: :collection
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
      
  get 'regions', to: 'regions#new'
  get 'cities', to: 'cities#new'
  get 'communes', to: 'communes#new'

  root 'campings#home'

  get  '*path' => redirect('campings/home')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :camping
  belongs_to :user
  belongs_to :campsite
  has_many :reviews, dependent: :destroy
  belongs_to :billing, optional: true
  enum status: [:pendiente, :pagar, :pagado]
  validates :check_in, :check_out, :adults_quantity, presence: true
  validates :adults_quantity, numericality: { only_integer: true }
  validates :price_per_day, :total_price, numericality: true

  def value_calc
    values = {}
    self.campsite.camping.plans.each do |plan|
      values[:adult] = plan.price if plan.season.months.include? self.check_in.month and plan.adult?
      values[:child] = plan.price if plan.season.months.include? self.check_in.month and plan.child?
    end
    if self.adults_quantity > 0
      values[:adult] *= self.adults_quantity
    elsif self.kids_quantity > 0 
      values[:child] *= self.kids_quantity
    end
    values
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    before_action :set_booking, only: [:show, :edit, :update, :destroy,:prepayment]
    before_action :set_camping, only: [:index,:create,:edit, :update,:show,:new]
    

    def index
      @bookings = Booking.where(camping_id: @camping)
    end

    def user_bookings
      @user_bookings = Booking.where(user_id: current_user)
    end
  
    def new
      authorize! :new, Booking
      @booking = Booking.new
    end
  
    def create
      campsite = @camping.campsites.where(status: false).first

      if campsite != nil
          booking = Booking.new(booking_params)
          booking.user = current_user
          booking.camping = @camping
          booking.campsite = campsite
          values = booking.value_calc
          booking.price_per_day = values[:adult] + values[:child]
          booking.total_price = booking.price_per_day * ((booking.check_out - booking.check_in).to_i)
          booking.booking_date = Date.today
        
          if booking.save
            redirect_to prepayment_camping_booking_path(@camping,booking.id), notice: "Se ha reservado con exito"
          else
            redirect_to new_camping_booking_path(@camping), alert: "No se pudo guardar reserva."
          end
       end
    end

    def prepayment
      authorize! :new, Booking
    end
  
    def show
    end
  
    def edit
      authorize! :new, Booking
    end
  
    def update
      if @booking.update(booking_params)
        redirect_to edit_camping_booking_path(@camping, @booking.id), notice: 'La reserva se ha actualizado con exito'
      else
        redirect_to edit_camping_booking_path(@camping, @booking.id), notice: 'No se ha podido actualizar el registro'
      end
    end
  
    def destroy
      @booking.destroy
      redirect_to campings_path, notice: 'El registro se ha eliminado con exito'
    end
  
    def search
    end
  
    private

    def set_booking
        @booking = Booking.find(params[:id])
    end
  
    def set_camping
      @camping = Camping.find(params[:camping_id])
    end
    
    def booking_params
      params.require(:booking).permit(:check_in,:check_out,:camping_id, :price_per_day,:total_price,:booking_date,:adults_quantity,:kids_quantity,:observations,:status)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="gtco-section border-bottom">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-6 animate-box">
					<h3>Completa el siguiente formulario para Reservar:</h3>
					<%= form_with(model: [@camping, @booking,], local: true) do |f| %>
						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :check_in, 'Desde:' %>
                                <%= f.date_field :check_in, class: "form-control"%>
							</div>
							
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :check_out, 'Hasta:' %>
                                <%= f.date_field :check_out, class: "form-control"%>
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :adults_quantity,'Cantidad Adultos:' %>
                                <%= f.number_field :adults_quantity, class: "form-control"%>
                            </div>
						</div>

                        <div class="row form-group">
							<div class="col-md-12">
								<%= f.label :kids_quantity,'Cantidad Niños:' %>
                                <%= f.number_field :kids_quantity, class: "form-control"%>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :observations, 'Observaciones:' %>
                                <%= f.text_area :observations, class: "form-control", cols: "30", rows: "10", placeholder: "Puedes indicarnos algun detalle sobre tu estadía, como por ejemplo tu hora de llegada :)" %>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :status, 'Paga Online?' %>
                               <%= f.check_box :status, {}, checked_value = "pagar", unchecked_value = "pendiente" %>
                            </div>
						</div>
						<div class="form-group">
                            <%= f.submit 'Reservar', class: "btn btn-primary"  %>
						</div>

					</form>	
                    <% end %>	
				</div>
				<div class="col-md-5 col-md-push-1 animate-box">
					
					<div class="gtco-contact-info">
						<h3>Información de Contacto</h3>
						<ul>
							<li>Dirección: <%= @camping.address %></li>
							<li>Teléfono: <a href="<%= @camping.phone %>"> <%= @camping.phone %></a></li>
							<li>Email: <a href="<%= @camping.email %>"> <%= @camping.email %></a></li>
							<li>Web: <a href="<%= @camping.web %>"> <%= @camping.web %></a></li>
                            <li>Facebook: <a href="<%= @camping.facebook %>"> Siguenos!</a></li>
						</ul>
					</div>


				</div>
				</div>
			</div>
		</div>
	</div>

app/views/bookings/edit.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
								
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>
	
	<div class="gtco-section border-bottom">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-6 animate-box">
					<h3>Datos Reserva:</h3>
					<h4>Recuerda que si te pagaron en el Camping debes marcar el cuadro 'Pagado' para que guardemos el registro.</h4>
					<%= form_with(model: [@camping, @booking,], local: true) do |f| %>
						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :status, 'Pagado' %>
                               <%= f.check_box :status, {}, checked_value = "pagado", unchecked_value = "pendiente" %>
                            </div>
						</div>

						<div class="form-group">
                            <%= f.submit 'Actualizar', class: "btn btn-primary"  %>
						</div>

					</form>	
                    <% end %>	
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/bookings/index.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
								
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>

<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Reservas de tu Camping:</h2>
				</div>
			</div>
			<div class="row">
				<% @bookings.each do |booking| %>
					<div class="price-box popular">
					<ul class="pricing-info">
							<h4>Reserva: <%= booking.id %></h4>
							<li>Check In: <%= booking.check_in %></li>
							<li>Check Out: <%= booking.check_out %></li>
							<li>Sitio: <%= booking.campsite.identifier %></li>
							<li>Precio Total: <%= booking.total_price.to_i %></li>
							<li>Estado Pago: <%= booking.status %></li>
							<li>Observaciones: <%= booking.observations %></li><br>
   							<%= link_to 'Editar',  edit_camping_booking_path(@camping,booking), class: "btn btn-primary btn-sm"%>
					</ul>
					</div>
							
			</div>
					<% end %>
			</div>
		</div>
	</div>

app/views/bookings/new.html.erb
<%= render 'shared/menu' %>
<main class="col-md-9 float-left col px-5 pl-md-2 pt-2 main">
    <h1>Nueva Reserva</h1>
    <div class="">
        <%= form_with(model: [@camping, @booking,], local: true) do |f| %>

            <div class="form-group">
                <%= f.label :check_in %>
                <%= f.date_field :check_in%>
            </div>

            <div class="form-group">
                <%= f.label :check_out %>
                <%= f.date_field :check_out%>
            </div>

            <div class="form-group">
                <%= f.label :adults_quantity %>
                <%= f.text_field :adults_quantity%>
            </div>

            <div class="form-group">
                <%= f.label :kids_quantity %>
                <%= f.text_field :kids_quantity%>
            </div>

            <div class="form-group">
                <%= f.label :observations %>
                <%= f.text_area :observations %>
            </div>

            <div class="form-group">
                <%= f.label :status, 'Paga Online?' %>
                <%= f.check_box :status, {}, checked_value = "pagar", unchecked_value = "pendiente" %>
            </div>
            
            <div class="actions">
                <%= f.submit %>
            </div>
        <% end %>
    </div>

</main>

app/views/bookings/prepayment.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-center">
					<div class="row row-mt-15em">

						<div class="col-md-12 mt-text animate-box" data-animate-effect="fadeInUp">
							<h1>Felicitaciones has reservado con nosotros!</h1>	
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
    <p><%= notice %></p>
    <p><%= alert %></p>
	<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
                
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading animate-box">
					<h2>Datos Reserva: </h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<ul class="fh5co-faq-list">
						<li class="animate-box">
                            <h4>Camping:</h4>
							<p><%=@booking.campsite.camping.name%></p>
						</li>
                        <li class="animate-box">
                            <h4>Sitio:</h4>
							<p><%=@booking.campsite.identifier%></p>
						</li>
                        <li class="animate-box">
                            <h4>Desde:</h4>
							<p><%=@booking.check_in%></p>
						</li>
                        <li class="animate-box">
                            <h4>Hasta:</h4>
							<p><%=@booking.check_out%></p>
						</li>
                        <li class="animate-box">
                            <h4>Precio por Día:</h4>
							<p><%=@booking.price_per_day.to_i%></p>
						</li>
                        <li class="animate-box">
                            <h4>Precio Total:</h4>
							<p><%=@booking.total_price.to_i%></p>
						</li>
                        <li class="animate-box">
                            <h4>Cantidad Adultos:</h4>
							<p><%=@booking.adults_quantity%></p>
						</li>
                        <li class="animate-box">
                            <h4>Cantidad Niños:</h4>
							<p><%=@booking.kids_quantity%></p>
						</li>
                        <li class="animate-box">
                            <h4>Observaciones:</h4>
							<p><%=@booking.observations%></p>
						</li>
                        <li class="animate-box">
							<%if @booking.status == 'pagar'%>
                            	<%= link_to 'Pagar', pre_pay_billings_path, class: 'btn btn-primary btn-sm' %>
							<% else %>
                            	<%= link_to 'Salir', root_path, class: 'btn btn-primary btn-sm' %>
							<% end %>
                        </li>
					</ul>
				</div>
			</div>
            
		</div>
	</div>

app/views/bookings/user_bookings.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
								
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>

<div class="gtco-section">
		<div class="gtco-container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
						<h2>Mis Reservas</h2>
					</div>
				</div>
				<div class="row">
					<% @user_bookings.each do |booking| %>
						<div class="price-box popular mr-50">
							<ul class="pricing-info">
									<h4>Reserva: <%= booking.id %></h4>
									<li>Camping: <%= booking.camping.name %></li>
									<li>Check In: <%= booking.check_in %></li>
									<li>Check Out: <%= booking.check_out %></li>
									<li>Sitio: <%= booking.campsite.identifier %></li>
									<li>Precio Total: <%= booking.total_price.to_i %></li>
									<li>Estado Pago: <%= booking.status %></li>
									<li>Observaciones: <%= booking.observations %></li><br>
									<% if booking.reviews.count == 0%>
										<%= link_to 'Escribir Review',  new_camping_booking_review_path(booking.camping_id,booking), class: "btn btn-primary btn-sm"%>
									<%elsif booking.reviews.count == 1%>
										<li>Ya escribiste un review <br>para esta reserva</li>
									<%end%>
							</ul>
						</div>
					<% end %>		
				</div>
					
		</div>
</div>