config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :campings do  
      get :home, on: :collection 
      get :search, on: :collection
      get :my_campings, on: :collection
      get :admin_camp, on: :member
      get :find_address, on: :collection
      resources :campsites
      resources :campservices
      resources :plans
      resources :bookings do
        get :prepayment, on: :member
        resources :reviews
      end
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  resources :users, only: [] do 
    get 'user_bookings', to: 'bookings#user_bookings'
    get :find_address, on: :collection
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
      
  get 'regions', to: 'regions#new'
  get 'cities', to: 'cities#new'
  get 'communes', to: 'communes#new'

  root 'campings#home'

  get  '*path' => redirect('campings/home')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new(user_type: 2) # guest user (not logged in)
      if user.person?
        can [:read], Camping
        can [:read, :create], [Booking, Review]
        can [:read, :update,:destroy], User, user_id: user.id
      elsif user.camping?
        can :manage, Camping, user_id: user.id
        can :manage, [Booking, Plan, Campsite]
      elsif user.guest?
        can :read, [Camping, Review]
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :currency
  belongs_to :user

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :camping
  belongs_to :user
  belongs_to :campsite
  has_many :reviews, dependent: :destroy
  belongs_to :billing, optional: true
  enum status: [:pendiente, :pagar, :pagado]
  validates :check_in, :check_out, :adults_quantity, presence: true
  validates :adults_quantity, numericality: { only_integer: true }
  validates :price_per_day, :total_price, numericality: true

  def value_calc
    values = {}
    self.campsite.camping.plans.each do |plan|
      values[:adult] = plan.price if plan.season.months.include? self.check_in.month and plan.adult?
      values[:child] = plan.price if plan.season.months.include? self.check_in.month and plan.child?
    end
    if self.adults_quantity > 0
      values[:adult] *= self.adults_quantity
    elsif self.kids_quantity > 0 
      values[:child] *= self.kids_quantity
    end
    values
  end

end

app/models/camping.rb
class Camping < ApplicationRecord
  belongs_to :user
  belongs_to :commune
  belongs_to :country, optional: true
  enum camping_type: [:camping, :patio]
  mount_uploaders :images, ImageUploader
  has_many :campsites
  has_and_belongs_to_many :services
  has_many :plans
  has_many :bookings, through: :campsites
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  validates :name, :user_id, :camping_type, :commune_id, presence: true

  def prom(id) 
    reviews = Review.where(booking_id: Booking.where(campsite_id: Campsite.where(camping_id: id)))
    
    if reviews.count > 0
      suma = 0
      reviews.each do |review|
        suma += review.ranking
      end

      @prom = suma / reviews.count
    else 
      @prom = 'No hay evaluaciones aun.'
    end

  end

end

app/models/campsite.rb
class Campsite < ApplicationRecord
  belongs_to :camping
  has_many :bookings
  validates :identifier, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :communes, dependent: :destroy
end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :city
  has_many :users
  has_many :campings
end

app/models/country.rb
class Country < ApplicationRecord
	has_many :regions, dependent: :destroy
end

app/models/currency.rb
class Currency < ApplicationRecord
    has_many :transactions
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :users
	validates :name, presence: true
end

app/models/paymentmethod.rb
class Paymentmethod < ApplicationRecord
    has_many :transactions
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :season
  belongs_to :camping
  enum person_type: [:child, :adult]
  validates :season_id, :camping_id, :price, :person_type, presence: true
  validates :price, numericality: { only_integer: true }
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :comment, :ranking, presence: true
end

app/models/season.rb
class Season < ApplicationRecord
    has_many :plans
    validates :name, presence: true

    # Este metodo soluciona la comparación de meses para identificar la temporada.
    # Analizar la necesidad de remover los campos start_date y end_date en tabla seasons.
    def months
        if self.name == 'Alta'
            [11,12,1,2,3]
        else
            [4,5,6,7,8,9,10]
        end
    end
end

app/models/service.rb
class Service < ApplicationRecord
	has_and_belongs_to_many :campings, dependent: :destroy
	has_many :plans
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum user_type: [:person, :camping, :guest]
  belongs_to :commune, optional: true 
  belongs_to :city, optional: true 
  belongs_to :region, optional:true 
  belongs_to :country, optional: true
  belongs_to :genre, optional: true
  has_many :campings
  mount_uploader :image, ImageUploader
  has_many :bookings
  has_many :reviews, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  validates :email, :user_type, presence: true

  def pay
  	bookings.where(status: 'pagar')
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChileCamp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'camping', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="gtco-loader"></div>
    <div id="page"> 
    <%= render 'shared/navbar'%>
    <%= yield %>  
    <%= render 'shared/footer'%>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="//maps.google.com/maps/api/js?key=AIzaSyAoVUWWgB90Fu64guAMa-Y7T9nmwn0EQ9c"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer id="gtco-footer" role="contentinfo">
		<div class="gtco-container">
			<div class="row row-p	b-md">

				<div class="col-md-4">
					<div class="gtco-widget">
						<h3>Sobre Nosotros</h3>
						<p>ChileCamp es una iniciativa creada a partir de la pasión que tenemos por el camping y nuestro hermoso país llamado Chile, aventurate a conocerlo con nosotros!</p>
					</div>
				</div>

				<div class="col-md-3 col-md-push-1">
					<div class="gtco-widget">
						<h3>Contactanos</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#">+ 56 234 567 890</a></li>
							<li><a href="#">info@chilecamp.cl</a></li>
						</ul>
					</div>
				</div>

			</div>

			<div class="row copyright">
				<div class="col-md-12">
					<p class="pull-left">
						<small class="block">&copy; 2018 ChileCamp. Todos los derechos reservados.</small> 
					</p>
					<p class="pull-right">
						<ul class="gtco-social-icons pull-right">
							<li><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#"><i class="fab fa-facebook-square"></i></a></li>
							<li><a href="#"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>

app/views/shared/_navbar.html.erb
  <nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			
			<div class="row">
				<div class="col-sm-4 col-xs-12">
					<div id="gtco-logo"><a href="<%= root_path %>">ChileCamp<em>.</em></a></div>
				</div>
				<div class="col-xs-8 text-right menu-1">
					<ul>	
					<% if user_signed_in? && current_user.user_type == 'person'%>
						<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
						<li><a href="<%= edit_user_registration_path %>">Perfil Usuario</a></li>
						<li><a href="<%= user_user_bookings_path(current_user) %>">Mis Reservas</a></li>
						<li><a href="<%= campings_path %>">Encuentra tu Camping</a></li>
					<% elsif user_signed_in? && current_user.user_type == 'camping'%>
						<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
						<li><a href="<%= my_campings_campings_path %>">Mis Campings</a></li>
						<li><a href="<%= new_camping_path %>">Crea tu Camping</a></li>
					<% else %>
						<li><a href="<%= new_user_session_path %>">Iniciar Sesión</a></li>
						<li><a href="<%= new_user_registration_path %>">Registrarse</a></li>
					<% end %>
					</ul>
					
				</div>
			</div>
			
		</div>
	</nav>