config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :campings do  
      get :home, on: :collection 
      get :search, on: :collection
      get :my_campings, on: :collection
      get :admin_camp, on: :member
      get :find_address, on: :collection
      resources :campsites
      resources :campservices
      resources :plans
      resources :bookings do
        get :prepayment, on: :member
        resources :reviews
      end
  end

  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }

  resources :users, only: [] do 
    get 'user_bookings', to: 'bookings#user_bookings'
    get :find_address, on: :collection
  end

  resources :billings, only: [] do
    collection do
      get 'pre_pay'
      get 'execute'
    end
  end
      
  get 'regions', to: 'regions#new'
  get 'cities', to: 'cities#new'
  get 'communes', to: 'communes#new'

  root 'campings#home'

  get  '*path' => redirect('campings/home')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :season
  belongs_to :camping
  enum person_type: [:child, :adult]
  validates :season_id, :camping_id, :price, :person_type, presence: true
  validates :price, numericality: { only_integer: true }
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
	before_action :set_camping
	before_action :set_plan, only: [:show, :edit, :update, :destroy]
	authorize_resource

	def index
		@plans = Plan.where(camping_id: @camping)
	end

	def new
		@plan = Plan.new 
		@seasons = Season.all.map{|s|[s.name, s.id]}
		@plans = Plan.all

	end

	def create
		plan = Plan.new(plan_params)
		plan.camping_id = params[:camping_id]

		if plan.save
      		redirect_to camping_plans_path, notice: 'Se creo plan con exito'
    	else
      		redirect_to new_camping_plan_path, notice: 'No se pudo crear plan :('
    	end
	end

	def edit
		@plans = Plan.all
		@seasons = Season.all.map{|s|[s.name, s.id]}
	end

	def update
		if @plan.update(plan_params)
			redirect_to camping_plans_path, notice: 'El plan se ha actualizado con exito'
		else
            redirect_to edit_camping_plan_path(@plan.id), notice: 'No se ha podido actualizar el registro'
		end
	end

	def destroy
		if @plan.destroy
			redirect_to camping_plans_path(@camping), notice: 'El registro se ha eliminado con exito'
		else 
			redirect_to camping_plans_path(@camping), alert: 'No se ha podido eliminar registro.'
		end
	end

	private

	def set_plan
      @plan = Plan.find(params[:id])
	end

    def set_camping
      @camping = Camping.find(params[:camping_id])
    end

	def plan_params
		params.require(:plan).permit(:person_type, :camping_id, :price, :season_id)
	end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<div class="gtco-section border-bottom">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-6 animate-box">
					<h3>Plan:</h3>
					<%= form_with(model: [@camping, @plan], local: true) do |f| %>

						<div class="row form-group">
							<div class="col-md-12">
								<%= f.label :person_type,'Tipo Persona:' %>
                                <%= f.select :person_type, Plan.person_types.keys, class: "form-control"  %>
                            </div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :season, 'Temporada:' %>
                                <%= f.select :season_id, options_for_select(@seasons),{prompt: 'Seleccione Temporada'}, {id: 'season'}%>
                            </div>
						</div>

                        <div class="row form-group">
							<div class="col-md-12">
                                <%= f.label :price, 'Precio:' %>
                                <%= f.number_field :price, class: "form-control"%>
                            </div>
						</div>

						<div class="form-group">
                            <%= f.submit 'Guardar', class: "btn btn-primary"  %>
						</div>

					</form>	
                    <% end %>	
				</div>
				</div>
			</div>
		</div>
	</div>

app/views/plans/edit.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
								
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>
	
<%= render 'form'%>

<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Planes de tu Camping:</h2>
				</div>
			</div>
			<div class="row">
				<% @plans.each do |plan| %>
					<div class="col-lg-4 col-md-4 col-sm-6">
							<div class="price-box popular">
								<h3>Temporada <%= plan.season.name %></h3>
								<p><%= if plan.person_type == 'adult' then 'Adulto' else 'Niño' end %>: <%= plan.price %></p>
								<%= link_to 'Editar',  edit_camping_plan_path(@camping,plan), class: "btn btn-primary btn-sm"%>								
							</div>
							<br>
					</div>
					<% end %>
			</div>
		</div>
	</div>

app/views/plans/index.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
								
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>

<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Planes de tu Camping:</h2>
				</div>
			</div>
			<div class="row">
				<%if @plans.empty?%>
					<h4>Aun no tienes planes creados.</h4>
				<%else%>	
					<% @plans.each do |plan| %>
						<div class="col-lg-4 col-md-4 col-sm-6">
								<div class="price-box popular">
									<h3>Temporada <%= plan.season.name %></h3>
									<p><%= if plan.person_type == 'adult' then 'Adulto' else 'Niño' end %>: <%= plan.price %></p>
									<%= link_to 'Editar',  edit_camping_plan_path(@camping,plan), class: "btn btn-primary btn-sm"%>								
									<%= link_to 'Eliminar', camping_plan_path(@camping,plan), method: :delete, class: "btn btn-primary btn-sm"%>								
								</div>
								<br>
						</div>
					<% end %>
				<%end%>
			</div>
			<%= link_to 'Crear Plan',  new_camping_plan_path(@camping), class: "btn btn-primary btn-sm"%>
		</div>
	</div>

app/views/plans/new.html.erb
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					<div class="row row-mt-15em">

						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
								
						</div>
						
					</div>
					
				</div>
			</div>
		</div>
	</header>
	
    <p><%= notice %></p>
    <p><%= alert %></p>
	
<%= render 'form'%>

<div class="gtco-section">
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center gtco-heading">
					<h2>Planes de tu Camping:</h2>
				</div>
			</div>
			<div class="row">
				<% @plans.each do |plan| %>
					<div class="col-lg-4 col-md-4 col-sm-6">
							<div class="price-box popular">
								<h3>Temporada <%= plan.season.name %></h3>
								<p><%= if plan.person_type == 'adult' then 'Adulto' else 'Niño' end %>: <%= plan.price %></p>
								<%= link_to 'Editar',  edit_camping_plan_path(@camping,plan), class: "btn btn-primary btn-sm"%>								
							</div>
							<br>
					</div>
					<% end %>
			</div>
		</div>
	</div>